window.GRAPH_SEED = {
  meta: {
    title: "Japan Trip Graph Workspace",
    updatedAt: "2026-03-12",
    source: "Current pricing and schedule snapshot",
  },
  nodes: [
    {
      id: "window",
      type: "TripWindow",
      title: "3/22-3/24 비교 창",
      x: 80,
      y: 120,
      properties: {
        depart_after: "2026-03-22 19:00 KST",
        return_by: "2026-03-24 23:59 KST",
        origin: "동대구",
        preference: "최저가 중심",
      },
      notes:
        "출발은 3월 22일 일요일 저녁 7시 이후, 복귀는 3월 24일 화요일 아무때나 가능.",
    },
    {
      id: "constraint_depart",
      type: "Constraint",
      title: "출발 제약",
      x: 80,
      y: 340,
      properties: {
        label: "3/22 19:00 이후 출발",
      },
      notes: "당일 밤 바로 일본 입국 가능한 선택지는 제한적.",
    },
    {
      id: "constraint_icn",
      type: "Constraint",
      title: "복귀 선호",
      x: 80,
      y: 520,
      properties: {
        label: "가능하면 인천 귀국",
      },
      notes: "완성형 일정 판단에서 가장 큰 기준.",
    },
    {
      id: "scenario_fukuoka",
      type: "Scenario",
      title: "후쿠오카",
      x: 420,
      y: 60,
      properties: {
        status: "recommended",
        endpoint: "ICN",
        total_krw_min: "429369",
        total_krw_max: "475904",
      },
      notes: "인천 귀국까지 포함하면 가장 단순하고 현실적인 동선.",
    },
    {
      id: "scenario_tsushima",
      type: "Scenario",
      title: "대마도",
      x: 420,
      y: 350,
      properties: {
        status: "cheapest_if_busan_return_ok",
        endpoint: "Busan",
        total_krw_min: "262280",
        total_krw_max: "309115",
      },
      notes: "부산 왕복까지 허용하면 총액 최저.",
    },
    {
      id: "scenario_osaka",
      type: "Scenario",
      title: "오사카",
      x: 420,
      y: 640,
      properties: {
        status: "not_recommended",
        endpoint: "ICN",
      },
      notes: "2026-03-23 김해->간사이 직항 검색 결과가 비어 성립이 불안정.",
    },
    {
      id: "rail_ddg_busan",
      type: "Transport",
      title: "동대구 -> 부산 철도",
      x: 780,
      y: 70,
      properties: {
        mode: "rail",
        price_krw_min: "12000",
        price_krw_max: "17100",
        duration: "50m~1h",
      },
      notes: "KTX/SRT 일반실 기준 참고 범위.",
    },
    {
      id: "busan_lodging",
      type: "Lodging",
      title: "부산 1박",
      x: 780,
      y: 220,
      properties: {
        price_krw_min: "33466",
        price_krw_max: "75201",
        nights: "1",
      },
      notes: "부산역/항만 접근성 기준 저가~실용 가격대.",
    },
    {
      id: "pus_fuk_flight",
      type: "Transport",
      title: "김해 -> 후쿠오카 항공",
      x: 780,
      y: 410,
      properties: {
        mode: "flight",
        price_krw_min: "141000",
        duration: "1h",
        price_basis: "near-date current search",
      },
      notes: "동일 날짜 인덱스가 약해 근접 날짜 현재가를 기준값으로 사용.",
    },
    {
      id: "fukuoka_lodging",
      type: "Lodging",
      title: "후쿠오카 1박",
      x: 780,
      y: 590,
      properties: {
        price_krw_min: "111093",
        nights: "1",
      },
      notes: "하카타권 실용 숙소 현재가 예시.",
    },
    {
      id: "fuk_icn_flight",
      type: "Transport",
      title: "후쿠오카 -> 인천 항공",
      x: 1120,
      y: 410,
      properties: {
        mode: "flight",
        price_krw_min: "131810",
        duration: "1h30m",
      },
      notes: "2026-03-24 실시간 검색값 기준.",
    },
    {
      id: "busan_hitakatsu_ferry",
      type: "Transport",
      title: "부산 <-> 히타카츠 배편",
      x: 780,
      y: 860,
      properties: {
        mode: "ferry",
        price_krw: "120000",
        outbound: "2026-03-23 08:40->10:00",
        inbound: "2026-03-24 17:10->18:30",
      },
      notes: "사용자 제공 실예약 조건 반영.",
    },
    {
      id: "tsushima_lodging",
      type: "Lodging",
      title: "히타카츠 1박",
      x: 1120,
      y: 860,
      properties: {
        price_krw_min: "96814",
        nights: "1",
      },
      notes: "히타카츠 숙소 현재 예시값.",
    },
    {
      id: "kix_icn_flight",
      type: "Transport",
      title: "간사이 -> 인천 항공",
      x: 780,
      y: 1080,
      properties: {
        mode: "flight",
        price_jpy_min: "13900",
        duration: "2h",
      },
      notes: "귀국편 자체는 있으나 출국편이 문제.",
    },
    {
      id: "evidence_fuk_icn",
      type: "PriceEvidence",
      title: "FUK -> ICN 근거",
      x: 1450,
      y: 300,
      properties: {
        url: "https://dsk.ne.jp/m/FUK-ICN/20260324/",
      },
      notes: "2026-03-24 최저가 14,130엔 / 131,810원 확인.",
    },
    {
      id: "evidence_pus_kix",
      type: "PriceEvidence",
      title: "PUS -> KIX 근거",
      x: 1120,
      y: 1080,
      properties: {
        url: "https://dsk.ne.jp/m/PUS-KIX/20260323/",
      },
      notes: "2026-03-23 직항 검색 결과 없음.",
    },
    {
      id: "evidence_tsushima_user",
      type: "PriceEvidence",
      title: "대마도 사용자 제시값",
      x: 1450,
      y: 760,
      properties: {
        source: "user-provided",
      },
      notes: "왕복 12만원, 08:40->10:00 / 17:10->18:30.",
    },
    {
      id: "verdict_complete",
      type: "Verdict",
      title: "완성형 최적",
      x: 1450,
      y: 100,
      properties: {
        result: "후쿠오카",
      },
      notes: "인천 귀국 포함 시 후쿠오카가 가장 안정적.",
    },
    {
      id: "verdict_cheapest",
      type: "Verdict",
      title: "순수 최저가",
      x: 1450,
      y: 540,
      properties: {
        result: "대마도",
      },
      notes: "최종 부산 복귀 허용 시 총액 최저.",
    },
  ],
  edges: [
    { id: "e1", from: "window", to: "constraint_depart", label: "HAS_CONSTRAINT" },
    { id: "e2", from: "window", to: "constraint_icn", label: "HAS_CONSTRAINT" },
    { id: "e3", from: "window", to: "scenario_fukuoka", label: "COMPARES" },
    { id: "e4", from: "window", to: "scenario_tsushima", label: "COMPARES" },
    { id: "e5", from: "window", to: "scenario_osaka", label: "COMPARES" },
    { id: "e6", from: "scenario_fukuoka", to: "rail_ddg_busan", label: "USES" },
    { id: "e7", from: "scenario_fukuoka", to: "busan_lodging", label: "STAYS" },
    { id: "e8", from: "scenario_fukuoka", to: "pus_fuk_flight", label: "USES" },
    { id: "e9", from: "scenario_fukuoka", to: "fukuoka_lodging", label: "STAYS" },
    { id: "e10", from: "scenario_fukuoka", to: "fuk_icn_flight", label: "USES" },
    { id: "e11", from: "scenario_fukuoka", to: "evidence_fuk_icn", label: "SUPPORTED_BY" },
    { id: "e12", from: "scenario_fukuoka", to: "verdict_complete", label: "SELECTED_AS" },
    { id: "e13", from: "scenario_tsushima", to: "rail_ddg_busan", label: "USES" },
    { id: "e14", from: "scenario_tsushima", to: "busan_lodging", label: "STAYS" },
    { id: "e15", from: "scenario_tsushima", to: "busan_hitakatsu_ferry", label: "USES" },
    { id: "e16", from: "scenario_tsushima", to: "tsushima_lodging", label: "STAYS" },
    { id: "e17", from: "scenario_tsushima", to: "evidence_tsushima_user", label: "SUPPORTED_BY" },
    { id: "e18", from: "scenario_tsushima", to: "verdict_cheapest", label: "SELECTED_AS" },
    { id: "e19", from: "scenario_osaka", to: "rail_ddg_busan", label: "USES" },
    { id: "e20", from: "scenario_osaka", to: "kix_icn_flight", label: "CONSIDERS" },
    { id: "e21", from: "scenario_osaka", to: "evidence_pus_kix", label: "SUPPORTED_BY" },
  ],
};
